export const APP_CONFIG = {
  name:           'Vela',
  version:        '1.0.0',
  bundleId:       'com.vela.cycle',
  dbName:         'vela.db',
  pinLength:      4,
  maxPinAttempts: 5,
  lockoutMinutes: 5,
  premium: {
    monthly:      2.99,
    yearly:       14.99,
    lifetime:     9.99,
    trialDays:    7,
    currency:     'GBP',
  },
  prediction: {
    minCyclesForPrediction: 1,
    maxCyclesUsed:          6,
    defaultCycleLength:     28,
    defaultPeriodLength:    5,
    lutealPhaseLength:      14,
    minCycleLength:         20,
    maxCycleLength:         45,
    minPeriodLength:        2,
    maxPeriodLength:        9,
  },
}

export const SETTINGS_KEYS = {
  THEME:                    'theme',
  PIN_HASH:                 'pin_hash',
  BIOMETRIC_ENABLED:        'biometric_enabled',
  AVG_CYCLE_LENGTH:         'average_cycle_length',
  AVG_PERIOD_LENGTH:        'average_period_length',
  NOTIFICATIONS_ENABLED:    'notifications_enabled',
  NOTIFY_DAYS_BEFORE:       'notify_period_days_before',
  NOTIFY_FERTILE:           'notify_fertile_window',
  NOTIFY_OVULATION:         'notify_ovulation',
  ONBOARDING_COMPLETE:      'onboarding_complete',
  IS_PREMIUM:               'is_premium',
  PREMIUM_EXPIRES_AT:       'premium_expires_at',
  FIRST_DAY_OF_WEEK:        'first_day_of_week',
  TEMPERATURE_UNIT:         'temperature_unit',
  MOOD_VISIBLE_PREFIX:      'mood_visible_',
} as const
