export interface ThemeColors {
  // Brand
  primary:          string
  primaryLight:     string
  primaryDark:      string
  primaryFaint:     string
  // Accent
  fertile:          string
  fertileLight:     string
  ovulation:        string
  ovulationLight:   string
  // Neutrals
  background:       string
  surface:          string
  surfaceAlt:       string
  border:           string
  borderStrong:     string
  // Text
  textPrimary:      string
  textSecondary:    string
  textTertiary:     string
  textInverse:      string
  // Feedback
  success:          string
  successLight:     string
  warning:          string
  warningLight:     string
  error:            string
  errorLight:       string
  info:             string
  infoLight:        string
  // Calendar
  dayPeriod:        string
  dayPeriodText:    string
  dayFertile:       string
  dayFertileText:   string
  dayOvulation:     string
  dayOvulationText: string
  dayPredicted:     string
  dayPredictedText: string
  dayToday:         string
  dayDefault:       string
  dayDefaultText:   string
  dayMuted:         string
  // Tab bar
  tabActive:        string
  tabInactive:      string
  tabBackground:    string
}

export const RoseTheme: ThemeColors = {
  primary:          '#E8748A',
  primaryLight:     '#F4A7B5',
  primaryDark:      '#C4506A',
  primaryFaint:     '#FDF0F2',
  fertile:          '#C084FC',
  fertileLight:     '#EDE9FE',
  ovulation:        '#A855F7',
  ovulationLight:   '#F3E8FF',
  background:       '#FFFBFC',
  surface:          '#FFFFFF',
  surfaceAlt:       '#FDF4F6',
  border:           '#F3D4DA',
  borderStrong:     '#E8A0AF',
  textPrimary:      '#2D1B24',
  textSecondary:    '#7A5060',
  textTertiary:     '#B8899A',
  textInverse:      '#FFFFFF',
  success:          '#4CAF88',
  successLight:     '#E8F7F2',
  warning:          '#F59E4A',
  warningLight:     '#FEF3E2',
  error:            '#E85555',
  errorLight:       '#FDEAEA',
  info:             '#6B9FD4',
  infoLight:        '#EBF3FB',
  dayPeriod:        '#E8748A',
  dayPeriodText:    '#FFFFFF',
  dayFertile:       '#C084FC',
  dayFertileText:   '#5B21B6',
  dayOvulation:     '#A855F7',
  dayOvulationText: '#FFFFFF',
  dayPredicted:     '#F9C8D1',
  dayPredictedText: '#C4506A',
  dayToday:         '#2D1B24',
  dayDefault:       '#FFFFFF',
  dayDefaultText:   '#2D1B24',
  dayMuted:         '#F9F9F9',
  tabActive:        '#E8748A',
  tabInactive:      '#B8899A',
  tabBackground:    '#FFFFFF',
}

export const LavenderTheme: ThemeColors = {
  primary:          '#9B8EC4',
  primaryLight:     '#C4BAE3',
  primaryDark:      '#6D5FA3',
  primaryFaint:     '#F4F2FB',
  fertile:          '#F472B6',
  fertileLight:     '#FCE7F3',
  ovulation:        '#EC4899',
  ovulationLight:   '#FDF2F8',
  background:       '#FAFAFF',
  surface:          '#FFFFFF',
  surfaceAlt:       '#F6F4FD',
  border:           '#DDD8EF',
  borderStrong:     '#B8AFDA',
  textPrimary:      '#1E1830',
  textSecondary:    '#5C5278',
  textTertiary:     '#9E96BC',
  textInverse:      '#FFFFFF',
  success:          '#4CAF88',
  successLight:     '#E8F7F2',
  warning:          '#F59E4A',
  warningLight:     '#FEF3E2',
  error:            '#E85555',
  errorLight:       '#FDEAEA',
  info:             '#6B9FD4',
  infoLight:        '#EBF3FB',
  dayPeriod:        '#9B8EC4',
  dayPeriodText:    '#FFFFFF',
  dayFertile:       '#F472B6',
  dayFertileText:   '#9D174D',
  dayOvulation:     '#EC4899',
  dayOvulationText: '#FFFFFF',
  dayPredicted:     '#DDD8EF',
  dayPredictedText: '#6D5FA3',
  dayToday:         '#1E1830',
  dayDefault:       '#FFFFFF',
  dayDefaultText:   '#1E1830',
  dayMuted:         '#F9F9FF',
  tabActive:        '#9B8EC4',
  tabInactive:      '#C4B8D8',
  tabBackground:    '#FFFFFF',
}

export const SageTheme: ThemeColors = {
  primary:          '#7BAF8E',
  primaryLight:     '#A8CCB5',
  primaryDark:      '#4F8A66',
  primaryFaint:     '#F0F7F3',
  fertile:          '#82C5BE',
  fertileLight:     '#E0F5F3',
  ovulation:        '#44A899',
  ovulationLight:   '#CCEEEB',
  background:       '#FAFCFB',
  surface:          '#FFFFFF',
  surfaceAlt:       '#F3F8F5',
  border:           '#C8E0D0',
  borderStrong:     '#96C4A8',
  textPrimary:      '#1A2E24',
  textSecondary:    '#456053',
  textTertiary:     '#8AAE98',
  textInverse:      '#FFFFFF',
  success:          '#4CAF88',
  successLight:     '#E8F7F2',
  warning:          '#F59E4A',
  warningLight:     '#FEF3E2',
  error:            '#E85555',
  errorLight:       '#FDEAEA',
  info:             '#6B9FD4',
  infoLight:        '#EBF3FB',
  dayPeriod:        '#7BAF8E',
  dayPeriodText:    '#FFFFFF',
  dayFertile:       '#82C5BE',
  dayFertileText:   '#134E4A',
  dayOvulation:     '#44A899',
  dayOvulationText: '#FFFFFF',
  dayPredicted:     '#C8E0D0',
  dayPredictedText: '#4F8A66',
  dayToday:         '#1A2E24',
  dayDefault:       '#FFFFFF',
  dayDefaultText:   '#1A2E24',
  dayMuted:         '#F5FAF7',
  tabActive:        '#7BAF8E',
  tabInactive:      '#B8D4C8',
  tabBackground:    '#FFFFFF',
}

export const MidnightTheme: ThemeColors = {
  primary:          '#C084FC',
  primaryLight:     '#DDB6FE',
  primaryDark:      '#9333EA',
  primaryFaint:     '#1E1230',
  fertile:          '#F472B6',
  fertileLight:     '#3D1530',
  ovulation:        '#EC4899',
  ovulationLight:   '#2D0F22',
  background:       '#0F0A1A',
  surface:          '#1A1128',
  surfaceAlt:       '#251840',
  border:           '#3D2F5C',
  borderStrong:     '#6B4FA0',
  textPrimary:      '#F4EEFF',
  textSecondary:    '#C4B0E0',
  textTertiary:     '#8A7AAA',
  textInverse:      '#0F0A1A',
  success:          '#4ADE80',
  successLight:     '#0F2A1C',
  warning:          '#FB923C',
  warningLight:     '#2A1500',
  error:            '#F87171',
  errorLight:       '#2A0A0A',
  info:             '#60A5FA',
  infoLight:        '#0A1A2A',
  dayPeriod:        '#C084FC',
  dayPeriodText:    '#0F0A1A',
  dayFertile:       '#F472B6',
  dayFertileText:   '#F4EEFF',
  dayOvulation:     '#EC4899',
  dayOvulationText: '#F4EEFF',
  dayPredicted:     '#3D2F5C',
  dayPredictedText: '#C084FC',
  dayToday:         '#C084FC',
  dayDefault:       '#1A1128',
  dayDefaultText:   '#F4EEFF',
  dayMuted:         '#140E20',
  tabActive:        '#C084FC',
  tabInactive:      '#8A7AAA',
  tabBackground:    '#1A1128',
}

export const THEMES = {
  rose:     RoseTheme,
  lavender: LavenderTheme,
  sage:     SageTheme,
  midnight: MidnightTheme,
} as const

export type ThemeName = keyof typeof THEMES
