const fs = require('fs');
const path = require('path');
const { withAppBuildGradle } = require('@expo/config-plugins');

// `android/` is fully regenerated by `expo prebuild`, so the release
// signingConfig has to be injected here rather than hand-edited — the
// Expo template ships with `release { signingConfig signingConfigs.debug }`,
// which is fine for `expo run:android` but Play Store won't accept (and
// even if it did, it isn't the identity we want signing real releases).
//
// The actual keystore + passwords live outside `android/` in
// `credentials/android/` (gitignored, not wiped by prebuild) — see
// credentials/android/README.md for how that keystore was generated and
// how to back it up. This plugin just points the release build at it.
const MARKER = '// withAndroidReleaseSigning';

function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    const contents = config.modResults.contents;
    if (contents.includes(MARKER)) {
      return config;
    }

    const propsPath = path.join(
      __dirname,
      '..',
      'credentials',
      'android',
      'release-keystore.properties',
    );
    if (!fs.existsSync(propsPath)) {
      // No keystore configured yet on this machine — leave the template's
      // debug-signed release config alone rather than failing the build.
      return config;
    }

    const props = Object.fromEntries(
      fs
        .readFileSync(propsPath, 'utf8')
        .split('\n')
        .map((line) => line.trim())
        .filter((line) => line && !line.startsWith('#'))
        .map((line) => {
          const idx = line.indexOf('=');
          return [line.slice(0, idx), line.slice(idx + 1)];
        }),
    );

    const keystorePath = path
      .join(__dirname, '..', 'credentials', 'android', 'release.keystore')
      .replace(/\\/g, '\\\\');

    const signingConfigBlock = `signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            ${MARKER}
            storeFile file('${keystorePath}')
            storePassword '${props.STORE_PASSWORD}'
            keyAlias '${props.KEY_ALIAS}'
            keyPassword '${props.KEY_PASSWORD}'
        }
    }`;

    let newContents = contents.replace(
      /signingConfigs\s*\{\s*debug\s*\{[^}]*\}\s*\}/,
      signingConfigBlock,
    );

    if (newContents === contents) {
      throw new Error(
        "withAndroidReleaseSigning: couldn't find the default debug signingConfigs block to patch — build.gradle structure may have changed.",
      );
    }

    // Point the release buildType at the new signingConfig instead of debug's.
    newContents = newContents.replace(
      /(release\s*\{\s*(?:\/\/[^\n]*\n\s*)*)signingConfig signingConfigs\.debug/,
      '$1signingConfig signingConfigs.release',
    );

    config.modResults.contents = newContents;
    return config;
  });
}

module.exports = withAndroidReleaseSigning;
